In [1]:
import pandas as pd

In [2]:
import numpy as np

### Test Data Accuracy Comparison

In [3]:
## Read data
data_concat_bert = pd.read_csv('BDdata/Concat_bert.csv')
data_unimodal_image = pd.read_csv('BDdata/Unimodal_image.csv')
data_unimodal_text = pd.read_csv('BDdata/Unimodal_text.csv')
data_mmbt = pd.read_csv('BDdata/mmbt.csv')
data_late_fusion = pd.read_csv('BDdata/Late_fusion.csv')

In [4]:
!ls BDdata

Concat_bert.csv     Unimodal_text.csv   late_fusion_val.csv test_unseen.jsonl
Late_fusion.csv     concat_bert_val.csv mmbt.csv            uni_text_val.csv
Uni_image_val.csv   dev_seen.jsonl      mmbt_val.csv
Unimodal_image.csv  dev_unseen.jsonl    test_seen.jsonl


In [11]:
truth_data = pd.read_json('BDdata/test_unseen.jsonl',lines=True)

In [ ]:
truth_data[]

In [6]:
truth_id = truth_data['id']

In [7]:
truth_label = truth_data['label']

In [8]:
truth = truth_id 

In [9]:
truth_id

0       15740
1       38794
2       60792
3       71824
4        4796
        ...  
1995    71352
1996     2164
1997     3587
1998    47839
1999    34281
Name: id, Length: 2000, dtype: int64

In [10]:
data_concat_bert

id     proba  label
0     15740  0.067281      0
1     38794  0.804931      1
2     60792  0.112230      0
3     71824  0.071473      0
4      4796  0.218671      0
...     ...       ...    ...
1995  71352  0.340365      0
1996   2164  0.074915      0
1997   3587  0.188597      0
1998  47839  0.366481      0
1999  34281  0.039815      0

[2000 rows x 3 columns]

In [17]:
from sklearn.metrics import accuracy_score


#### Accuracy Scores

In [12]:
accuracy_score(data_concat_bert['label'],truth_label)

0.6555

In [13]:
accuracy_score(data_unimodal_image['label'],truth_label)

0.612

In [14]:
accuracy_score(data_unimodal_text['label'],truth_label)

0.6365

In [15]:
accuracy_score(data_mmbt['label'],truth_label)

0.6505

In [16]:
accuracy_score(data_late_fusion['label'],truth_label)

0.6475

In [17]:
from sklearn.metrics import confusion_matrix

#### Confusion Matrix

In [18]:
confusion_matrix(data_concat_bert['label'],truth_label)

array([[1102,  541],
       [ 148,  209]])

In [19]:
confusion_matrix(data_unimodal_image['label'],truth_label)

array([[1156,  682],
       [  94,   68]])

In [20]:
confusion_matrix(data_unimodal_text['label'],truth_label)

array([[1061,  538],
       [ 189,  212]])

In [21]:
confusion_matrix(data_mmbt['label'],truth_label)

array([[1150,  599],
       [ 100,  151]])

In [22]:
confusion_matrix(data_late_fusion['label'],truth_label)

array([[1000,  455],
       [ 250,  295]])

#### F1 scores

In [23]:
from sklearn.metrics import f1_score
f1_score(data_concat_bert['label'],truth_label)

0.37759710930442636

In [24]:
f1_score(data_unimodal_image['label'],truth_label)

0.14912280701754388

In [25]:
f1_score(data_unimodal_text['label'],truth_label)

0.368375325803649

In [26]:
f1_score(data_mmbt['label'],truth_label)

0.3016983016983017

In [27]:
f1_score(data_late_fusion['label'],truth_label)

0.4555984555984556

In [18]:
output2 = data_mmbt[data_mmbt['label'] != truth_label]

In [19]:
output2[output2['label'] == 0]['id'] #False Negative 0-nonhateful

0      15740
2      60792
3      71824
4       4796
5      75310
       ...  
742    12594
744    10647
745    18732
747    32604
748    98013
Name: id, Length: 599, dtype: int64

In [22]:
output2[output2['label'] == 1]['id'][10:18] ## False Positive 1-hateful

874    41967
876    90617
882    56023
892    28576
894    62781
911    46759
922    58621
925    53148
Name: id, dtype: int64

In [31]:
data_concat_bert[data_unimodal_image['id'] == 49052]

id     proba  label
749  49052  0.917523      1

In [32]:
data_unimodal_text[data_unimodal_image['id'] == 49052]

id     proba  label
749  49052  0.912873      1

In [33]:
data_mmbt[data_unimodal_image['id'] == 49052]

id     proba  label
749  49052  0.838254      1

In [34]:
data_late_fusion[data_unimodal_image['id'] == 49052]

id     proba  label
749  49052  0.926233      1

## Validation Data Accuracy Comparison

In [38]:
truth_data1 = pd.read_json('BDdata/dev_unseen.jsonl',lines=True)

In [39]:
truth_data1

id            img  label  \
0    76432  img/76432.png      0   
1    14270  img/14270.png      0   
2    56947  img/56947.png      0   
3    35174  img/35174.png      0   
4    39264  img/39264.png      0   
..     ...            ...    ...   
535  83675  img/83675.png      0   
536  37198  img/37198.png      0   
537  48670  img/48670.png      0   
538   9863  img/09863.png      0   
539  97320  img/97320.png      0   

                                                  text  
0                      you thinking what i'm thinking?  
1                                     a brilliant mind  
2                   pro gamer 6.000.000 kills, 1 death  
3                                    lets end poaching  
4    my wife called me a good husband thats a huge ...  
..                                                 ...  
535                   i'm gonna be like phelps one day  
536  when you're so relaxed you can feel yourself g...  
537  look at this sandwich maker club i found on wi...  
538                             diverse group of women  
539  "when your dishwasher is broken so you take it...  

[540 rows x 4 columns]

In [40]:
truth_label1 = truth_data1['label']
truth_label1

0      0
1      0
2      0
3      0
4      0
      ..
535    0
536    0
537    0
538    0
539    0
Name: label, Length: 540, dtype: int64

In [41]:
data_concatBert_val = pd.read_csv('BDdata/concat_bert_val.csv')
data_uniImage_val = pd.read_csv('BDdata/Uni_image_val.csv')
data_uniText_val = pd.read_csv('BDdata/uni_text_val.csv')
data_mmbt_val = pd.read_csv('BDdata/mmbt_val.csv')
data_lateFusion_val = pd.read_csv('BDdata/late_fusion_val.csv')

In [42]:
!ls Bddata

Concat_bert.csv     Unimodal_text.csv   late_fusion_val.csv test_unseen.jsonl
Late_fusion.csv     concat_bert_val.csv mmbt.csv            uni_text_val.csv
Uni_image_val.csv   dev_seen.jsonl      mmbt_val.csv
Unimodal_image.csv  dev_unseen.jsonl    test_seen.jsonl


#### F1 scores

In [43]:
f1_score(data_concatBert_val['label'],truth_label1)

0.3389830508474576

In [44]:
f1_score(data_uniImage_val['label'],truth_label1)

0.14592274678111591

In [45]:
f1_score(data_uniText_val['label'],truth_label1)

0.3450479233226837

In [46]:
f1_score(data_mmbt_val['label'],truth_label1)

0.24521072796934865

In [47]:
f1_score(data_lateFusion_val['label'],truth_label1)

0.4092219020172911

#### Accuracy Scores

In [48]:
accuracy_score(data_concatBert_val['label'],truth_label1)

0.6388888888888888

In [49]:
accuracy_score(data_uniImage_val['label'],truth_label1)

0.6314814814814815

In [50]:
accuracy_score(data_uniText_val['label'],truth_label1)

0.6203703703703703

In [51]:
accuracy_score(data_mmbt_val['label'],truth_label1)

0.6351851851851852

In [52]:
accuracy_score(data_lateFusion_val['label'],truth_label1)

0.6203703703703703

#### Confusion Matrix

In [53]:
confusion_matrix(data_concatBert_val['label'],truth_label1)

array([[295, 150],
       [ 45,  50]])

In [54]:
confusion_matrix(data_uniImage_val['label'],truth_label1)

array([[324, 183],
       [ 16,  17]])

In [55]:
confusion_matrix(data_uniText_val['label'],truth_label1)

array([[281, 146],
       [ 59,  54]])

In [56]:
confusion_matrix(data_mmbt_val['label'],truth_label1)

array([[311, 168],
       [ 29,  32]])

In [57]:
confusion_matrix(data_lateFusion_val['label'],truth_label1)

array([[264, 129],
       [ 76,  71]])

# Ensembling Test Set

In [76]:
arr1 = np.array(data_concat_bert['label'])
arr2 = np.array(data_mmbt['label'])
arr3 = np.array(data_late_fusion['label'])
result = np.stack((arr1.T, arr2.T, arr3.T), axis=1)

[1 1 1]


In [78]:
from collections import Counter

In [96]:
array = []
for i in range(result.shape[0]):
    x = Counter(result[i])
    array.append(x.most_common(1)[0][0])
    
array = np.array(array)

345

In [95]:
model_ensemble = data_concat_bert.copy()

357

In [97]:
model_ensemble['label'] = array

### Ensemble accuracy, F1 scores and confusion matrix Test set

In [99]:
accuracy_score(model_ensemble['label'],truth_label)

0.6575

In [100]:
f1_score(model_ensemble['label'],truth_label)

0.3744292237442922

In [101]:
confusion_matrix(model_ensemble['label'],truth_label)

array([[1110,  545],
       [ 140,  205]])

# Ensembling Validation Set

In [102]:
arr1_val = np.array(data_concatBert_val['label'])
arr2_val = np.array(data_mmbt_val['label'])
arr3_val = np.array(data_lateFusion_val['label'])
result2 = np.stack((arr1_val.T, arr2_val.T, arr3_val.T), axis=1)

In [103]:
array2 = []
for i in range(result2.shape[0]):
    x = Counter(result[i])
    array2.append(x.most_common(1)[0][0])
    
array2 = np.array(array2)

In [104]:
model_ensemble_val = data_concatBert_val.copy()
model_ensemble_val['label'] = array2

### Ensemble accuracy, F1 scores and confusion matrix value set

In [105]:
accuracy_score(model_ensemble_val['label'],truth_label1)

0.5592592592592592

In [106]:
f1_score(model_ensemble_val['label'],truth_label1)

0.3081395348837209

In [107]:
confusion_matrix(model_ensemble_val['label'],truth_label1)

array([[249, 147],
       [ 91,  53]])

## Ensemble Goodness over individual model's false positives and false negatives

In [136]:
output_ensemble = model_ensemble[model_ensemble['label'] == truth_label]

In [137]:
output_ensemble[output_ensemble['label'] == 0]['id']

750     86405
751     81926
754     60315
755     45217
756     92640
        ...  
1995    71352
1996     2164
1997     3587
1998    47839
1999    34281
Name: id, Length: 1110, dtype: int64

In [138]:
output_ensemble[output_ensemble['label'] == 1]['id']

1      38794
6      63425
7      72360
11     78093
12      8179
       ...  
741    17934
743    31957
744    10647
746    84657
749    49052
Name: id, Length: 205, dtype: int64

In [158]:
data_concat_bert[data_concat_bert['id']==71352]

id     proba  label
1995  71352  0.340365      0

In [159]:
data_mmbt[data_mmbt['id']==71352]

id     proba  label
1995  71352  0.124255      0

In [160]:
data_late_fusion[data_late_fusion['id']==71352]

id     proba  label
1995  71352  0.717142      1